// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using week6Task.DbContexts;

#nullable disable

namespace week6Task.Migrations
{
    [DbContext(typeof(ContactsContexts))]
    [Migration("20230730215653_ContactsDBSeededMigration")]
    partial class ContactsDBSeededMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("week6Task.Entities.Contacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("PhoneNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Twitter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "lekki",
                            Name = "Khalid",
                            PhoneNumber = 8023932313L,
                            PhotoUrl = "img.jpg",
                            Twitter = "senkou"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ibadan",
                            Name = "james",
                            PhoneNumber = 8023932313L,
                            PhotoUrl = "img.jpg",
                            Twitter = "kiroii"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Abuja",
                            Name = "Javier",
                            PhoneNumber = 8023932313L,
                            PhotoUrl = "img.jpg",
                            Twitter = "Bgard"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Ondo",
                            Name = "David",
                            PhoneNumber = 8023932313L,
                            PhotoUrl = "img.jpg",
                            Twitter = "davido"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
